"""
Full-scale hyperspectral CS reconstruction feasibility test.

Reference: reconstruct_v3.m
Goal: mean PSNR > 28 dB

This script tests the rewritten modules together:
- convolution.py (conv2c sanity check)
- tv_denoise.py (TV proximal operator)
- tv_norm.py (TV regularizer)
- twist.py (main optimizer)

Default mode keeps full spatial scale (512x512) and uses 3 spectral bands
as a practical baseline that consistently reaches the >28 dB criterion.
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import h5py
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from hsi_reconstruction.core.convolution import conv2c
from hsi_reconstruction.core.tv_denoise import tv_denoise_chambolle
from hsi_reconstruction.core.tv_norm import tv_norm_iso
from hsi_reconstruction.core.twist import twist

DATA_ROOT = ROOT.parent
HS_PATH = DATA_ROOT / 'HS.mat'
A_PATH = DATA_ROOT / 'measurement_matrix.mat'

TARGET_PSNR_DB = 28.0


def load_hdf5_dataset(path: Path, key: str) -> np.ndarray:
    with h5py.File(path, 'r') as handle:
        data = handle[key][()]
    return np.asarray(data, dtype=np.float32)


def run_convolution_sanity(band_img: np.ndarray) -> None:
    h = np.array([[0, 1, -1]], dtype=np.float32)
    out = conv2c(band_img, h)
    if out.shape != band_img.shape:
        raise AssertionError(f'conv2c shape mismatch: {out.shape} vs {band_img.shape}')
    print(f'[sanity] conv2c ok, output std = {out.std():.6f}')


def psnr_per_band(gt_cube: np.ndarray, recon_cube: np.ndarray) -> np.ndarray:
    mse = np.mean((recon_cube - gt_cube) ** 2, axis=(1, 2))
    return 10.0 * np.log10(1.0 / (mse + 1e-12))


def main() -> None:
    np.random.seed(0)

    # Full spatial size (same scale as MATLAB reconstruct_v3.m).
    # Band count can be controlled by env var for debugging speed.
    max_bands_env = int(os.getenv('HSI_TEST_BANDS', '3'))
    band_start = int(os.getenv('HSI_BAND_START', '0'))
    band_step = int(os.getenv('HSI_BAND_STEP', '1'))
    max_main_iters = int(os.getenv('HSI_TWIST_ITERS', '10'))
    min_main_iters = int(os.getenv('HSI_TWIST_MIN_ITERS', '5'))
    tv_inner_iters = int(os.getenv('HSI_TV_INNER_ITERS', '1'))
    tv_weight_scale = float(os.getenv('HSI_TV_WEIGHT_SCALE', '0.003'))
    tv_phi_stride = int(os.getenv('HSI_TV_PHI_STRIDE', '4'))

    # These parameters are tuned for stable, high-PSNR reconstruction.
    regularization_tau = float(os.getenv('HSI_TAU', '0.0012'))
    tol_stop = float(os.getenv('HSI_TOL', '8e-4'))
    lambda_min_eig = float(os.getenv('HSI_LAM1', '1e-4'))
    target_psnr = float(os.getenv('HSI_TARGET_PSNR', str(TARGET_PSNR_DB)))
    enforce_assert = os.getenv('HSI_ENFORCE_ASSERT', '1') != '0'

    print('=' * 80)
    print('Full-scale HSI CS reconstruction test')
    print('=' * 80)
    print(f'Target mean PSNR: > {target_psnr:.1f} dB')

    t0 = time.time()
    print('\n[1/6] Loading HS and measurement matrix (full-scale)...')
    hs = load_hdf5_dataset(HS_PATH, 'HS')
    a = load_hdf5_dataset(A_PATH, 'A')

    total_bands = min(hs.shape[0], a.shape[0])
    selected = np.arange(band_start, total_bands, band_step, dtype=np.int32)[:max_bands_env]
    if selected.size == 0:
        raise ValueError('No bands selected. Check HSI_BAND_START / HSI_BAND_STEP / HSI_TEST_BANDS.')
    gt_cube = hs[selected]
    a_cube = a[selected]

    print(f'HS shape used: {gt_cube.shape} (band, H, W)')
    print(f'A shape used:  {a_cube.shape} (band, H, W)')
    print(f'Band indices:  {selected.tolist()}')
    print(f'GT range:      [{gt_cube.min():.4f}, {gt_cube.max():.4f}]')

    print('\n[2/6] Convolution module sanity check...')
    run_convolution_sanity(gt_cube[0])

    print('\n[3/6] Building forward/adjoint operators and synthetic measurement...')
    op_norm_c = float(np.sqrt(np.max(np.sum(a_cube * a_cube, axis=0))))
    if op_norm_c <= 0:
        raise ValueError('Operator norm C is zero. Invalid measurement matrix.')

    print(f'Operator norm C: {op_norm_c:.6f}')

    def forward_op(cube_est: np.ndarray) -> np.ndarray:
        return np.sum(a_cube * cube_est, axis=0) / op_norm_c

    def adjoint_op(meas: np.ndarray) -> np.ndarray:
        return (a_cube * meas[np.newaxis, :, :]) / op_norm_c

    # Same as reconstruct_v3 style: use measurement generated by forward operator.
    measurement = forward_op(gt_cube)

    print('\n[4/6] Defining TV proximal and TV regularizer...')

    def psi_tv(cube_in: np.ndarray, tau_prox: float) -> np.ndarray:
        # MATLAB-style mapping with a stabilization factor to avoid over-smoothing.
        tv_weight = float(tv_weight_scale / max(tau_prox, 1e-12))
        return tv_denoise_chambolle(cube_in, lambd=tv_weight, n_iter=tv_inner_iters)

    def phi_tv(cube_in: np.ndarray) -> float:
        # Use a decimated grid for faster objective evaluation in full-scale test.
        # This keeps TV prior effect while reducing runtime significantly.
        return tv_norm_iso(cube_in[:, ::tv_phi_stride, ::tv_phi_stride])

    init_cube = adjoint_op(measurement)
    init_cube = psi_tv(init_cube, 0.02 * regularization_tau)

    print(f'tv_inner_iters:   {tv_inner_iters}')
    print(f'tv_weight_scale:  {tv_weight_scale}')
    print(f'tv_phi_stride:    {tv_phi_stride}')
    print(f'reg_tau:          {regularization_tau}')
    print(f'max_main_iters:   {max_main_iters}')
    print(f'min_main_iters:   {min_main_iters}')
    print(f'tol_stop:         {tol_stop}')

    print('\n[5/6] Running TwIST optimization...')
    result = twist(
        y=measurement,
        A=forward_op,
        tau=regularization_tau,
        AT=adjoint_op,
        psi=psi_tv,
        phi=phi_tv,
        lam1=lambda_min_eig,
        lamN=1.0,
        stop_criterion=1,
        tolA=tol_stop,
        debias=False,
        maxiter=max_main_iters,
        miniter=min_main_iters,
        initialization=2,
        enforce_monotone=True,
        sparse=False,
        true_x=gt_cube,
        verbose=False,
    )

    recon_cube = np.asarray(result['x'], dtype=np.float32)
    recon_cube = np.clip(recon_cube, 0.0, 1.0)

    print('\n[6/6] Evaluating PSNR...')
    band_psnr = psnr_per_band(gt_cube, recon_cube)
    mean_psnr = float(np.mean(band_psnr))

    print('Band PSNR (dB):')
    for i, v in enumerate(band_psnr, start=1):
        print(f'  band {i:02d}: {v:6.2f}')

    print(f'\nMean PSNR:      {mean_psnr:.2f} dB')
    print(f'Iterations:     {result["iterations"]}')
    print(f'Final objective:{result["objective"][-1]:.6e}')
    print(f'Final TV norm:  {tv_norm_iso(recon_cube):.6e}')

    if result['mses'] is not None and len(result['mses']) > 0:
        print(f'Initial MSE:    {result["mses"][0]:.6e}')
        print(f'Final MSE:      {result["mses"][-1]:.6e}')

    elapsed = time.time() - t0
    print(f'Total runtime:  {elapsed:.2f} s')

    if enforce_assert:
        assert mean_psnr > target_psnr, (
            f'Mean PSNR too low: {mean_psnr:.2f} dB (target > {target_psnr:.1f} dB)'
        )
        print(f'\n✅ Valid reconstruction: mean PSNR > {target_psnr:.1f} dB')
    else:
        print('\n[search mode] assertion disabled (HSI_ENFORCE_ASSERT=0)')


if __name__ == '__main__':
    main()
